# NovaGen Research Labs

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier

# creating a baseline model

In [8]:
df= pd.read_csv("novagen_dataset.csv")
x=df.drop("Target", axis=1)
y=df["Target"]

In [9]:
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42,stratify=y)

In [11]:
scaler=StandardScaler()

x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [14]:
#logisitc Regression (with Regulaization)
log_reg=LogisticRegression(
    penalty='l2',
    solver='liblinear',
    max_iter=1000
)
log_reg.fit(x_train_scaled,y_train)
y_pred_lr=log_reg.predict(x_test_scaled)

#in this model evaluation, Recall is more important than accuracy
# because missing a high-risk patient is dangerous

print("Logistic Regression Accuracy:", accuracy_score(y_test,y_pred_lr))
print('Logisitc Regression recall:', recall_score(y_test,y_pred_lr))
print(classification_report(y_test,y_pred_lr))

Logistic Regression Accuracy: 0.8141361256544503
Logisitc Regression recall: 0.8283132530120482
              precision    recall  f1-score   support

           0       0.81      0.80      0.80       914
           1       0.82      0.83      0.82       996

    accuracy                           0.81      1910
   macro avg       0.81      0.81      0.81      1910
weighted avg       0.81      0.81      0.81      1910

# Model2 KNN

In [17]:
knn=KNeighborsClassifier(
    n_neighbors=5,
    metric="euclidean")
knn.fit(x_train_scaled,y_train)
y_pred_knn=knn.predict(x_test_scaled)
print('knn accuracy:',accuracy_score(y_test,y_pred_knn))
print('knn recall:', recall_score(y_test,y_pred_knn))
print(classification_report(y_test,y_pred_knn))

knn accuracy: 0.8832460732984293
knn recall: 0.8835341365461847
              precision    recall  f1-score   support

           0       0.87      0.88      0.88       914
           1       0.89      0.88      0.89       996

    accuracy                           0.88      1910
   macro avg       0.88      0.88      0.88      1910
weighted avg       0.88      0.88      0.88      1910

In [19]:
df= pd.read_csv("novagen_dataset.csv")
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

# random forest ensemble

In [20]:
rf=RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42)
rf.fit(x_train,y_train)
y_pred_rf=rf.predict(x_test)

print("random forest acc:", accuracy_score(y_test,y_pred_rf))
print("random forest recall", recall_score(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))

random forest acc: 0.937696335078534
random forest recall 0.9588353413654619
              precision    recall  f1-score   support

           0       0.95      0.91      0.93       914
           1       0.92      0.96      0.94       996

    accuracy                           0.94      1910
   macro avg       0.94      0.94      0.94      1910
weighted avg       0.94      0.94      0.94      1910

# Gradinet Boosting (ensemble Learning)

In [21]:
gb=GradientBoostingClassifier(
    n_estimators=150,
    learning_rate=0.1,
    max_depth=3,
    random_state=42)

gb.fit(x_train,y_train)
y_pred_gb=gb.predict(x_test)
print('gradinet acc', accuracy_score(y_test,y_pred_gb))
print('gradient recall', recall_score(y_test,y_pred_gb))
print(classification_report(y_test,y_pred_gb))

gradinet acc 0.9303664921465968
gradient recall 0.9497991967871486
              precision    recall  f1-score   support

           0       0.94      0.91      0.93       914
           1       0.92      0.95      0.93       996

    accuracy                           0.93      1910
   macro avg       0.93      0.93      0.93      1910
weighted avg       0.93      0.93      0.93      1910

# voting classifier (ensemble learning)

In [26]:
voting_clf=VotingClassifier(
    estimators=[
        ('lr', LogisticRegression(max_iter=100,solver='liblinear')),
        ('knn',KNeighborsClassifier(n_neighbors=5)),
        ('rf', RandomForestClassifier(n_estimators=200, random_state=42))
    ],
    voting='soft'
)

voting_clf.fit(x_train_scaled,y_train)
y_pred_vote=voting_clf.predict(x_test_scaled)

print("voting classififer acc:", accuracy_score(y_test,y_pred_vote))
print("voting classifier recall:", recall_score(y_test,y_pred_vote))
print(classification_report(y_test,y_pred_vote))

voting classififer acc: 0.9162303664921466
voting classifier recall: 0.9307228915662651
              precision    recall  f1-score   support

           0       0.92      0.90      0.91       914
           1       0.91      0.93      0.92       996

    accuracy                           0.92      1910
   macro avg       0.92      0.92      0.92      1910
weighted avg       0.92      0.92      0.92      1910

# result

In [27]:
import pandas as pd

results = {
    "Model": [
        "Logistic Regression",
        "KNN",
        "Random Forest",
        "Gradient Boosting",
        "Voting Classifier"
    ],
    "Recall": [
        82.8,
        88.3,
        95.8,
        94.9,
        93.07
    ]
}

results_df = pd.DataFrame(results)

results_df

                 Model  Recall
0  Logistic Regression   82.80
1                  KNN   88.30
2        Random Forest   95.80
3    Gradient Boosting   94.90
4    Voting Classifier   93.07

# Best Classifier that we should use for NovaGen(based on Recall) - Random Forest with accuracy of 93.7%